#!/usr/bin/env bash
set -e

command=""
args=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        -*)
            args+=("$1")
            if [[ "$2" && "$2" != -* ]]; then
                args+=("$2")
                shift
            fi
            ;;
        *)
            command="$1"
            shift
            break
            ;;
    esac
    shift
done

if [[ "$command" == "build" ]]; then
    exec depot "${args[@]}" build --load "$@"
else
    real_docker="$(which docker)"

    # If Docker is resolved to this file, find the real Docker binary
    self=$(readlink -f "${BASH_SOURCE[0]}")
    if [[ "$real_docker" == "$self" ]]; then
        real_docker="$(which -a docker | head -2 | tail -1)"
    fi

    if [[ -z "$command" ]]; then
        exec "$real_docker" "${args[@]}"
    else
        exec "$real_docker" "${args[@]}" "$command" "$@"
    fi
fi
